---
abstract: 'Class to send E-Mail'
author:
  - 'Sergei Svistunov <sergei-svistunov@yandex.ru>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: QBit-Application-Model-SendMail
requires:
  Exception: '0'
  MIME::Base64: '0'
  MIME::Lite: '0'
  QBit::Application::Model: '0'
  Template: '0'
  base: '0'
  qbit: '0'
version: '0.008'
x_serialization_backend: 'YAML::Tiny version 1.70'
